export const FETCH_ALBUM_REQUEST = 'FETCH_ALBUM_REQUEST';
export const FETCH_ALBUM_SUCCESS = 'FETCH_ALBUM_SUCCESS';
export const FETCH_ALBUM_FAILURE = 'FETCH_ALBUM_FAILURE';

export const FETCH_MUSICA_REQUEST = 'FETCH_MUSICA_REQUEST';
export const FETCH_MUSICA_SUCCESS = 'FETCH_MUSICA_SUCCESS';
export const FETCH_MUSICA_FAILURE = 'FETCH_MUSICA_FAILURE';

export const SAVE_MUSIC = 'SAVE_MUSIC';
export const CLEAR_MUSIC = 'CLEAR_MUSIC';

export const GUARDA_HISTORICO = 'GUARDA_HISTORICO';
